#!/bin/bash
start () {
  if [ "$lastCommand" != "start" ]
  then
    echo -e "$1\t>> $now : ${@:2}" 2>&1 | tee -a log-$day.txt
  fi
}

elapsed () {
  if [ "$lastCommand" == "start" ]
  then
    startTime=$(echo $last | cut -d ' ' -f 4)
    stE=$(date +%s -d ${startTime})
    endTime=$(echo $now | cut -d ' ' -f 2)
    etE=$(date +%s -d ${endTime})
    elapsed=`expr ${etE} - ${stE}`
    if [ "$1" == "log" ]
    then
      echo -e "$2\t>> $now : ${@:3}" 2>&1 | tee -a log-$day.txt
      echo "Worked: `date +%H:%M:%S -ud @${elapsed}`" >> log-$day.txt
    fi
    if [ "$1" == "check" ]
    then
      echo "$last"
    fi
    echo "Worked: `date +%H:%M:%S -ud @${elapsed}`"
  fi
}

day=$(date +%Y-%m-%d)
now=$(date '+%Y-%m-%d %H:%M:%S')
last=$(tail -1 log-$day.txt | head -1)
lastCommand=$(echo $last | cut -d ' ' -f 1)

if [ "$1" == "start" ]
then
  start $@
fi
if [ "$1" == "stop" ]
then
  elapsed "log" $@
fi
if [ "$1" == "check" ]
then 
  elapsed "check"
fi
